# Generated by Django 3.2.2 on 2021-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=14, verbose_name='Type')),
                ('fee_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'fee',
                'verbose_name_plural': 'fees',
            },
        ),
    ]
